baseURL = "http://example.org/"
languageCode = "en-us"
title = "Renate Rittler"
theme = "artist"

[[params]]
    description = "Im an artist from austria"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = -110

[[menu.main]]
    name = "Ã–lbilder"
    url = "/categories/oil"
    weight = -100

[[menu.main]]
    name = "Zeichnungen"
    pre = "<i class='fa fa-road'></i>"
    url = "/categories/drawn"
    weight = -90